---
- name: Extract Lifecycle Environment from All Satellite Hosts
  hosts: all  # Target all hosts
  gather_facts: yes
  tasks:
    - name: Get hostvars for each host
      debug:
        var: foreman_architecture_id
      loop: "{{ groups['all'] }}"
