---
- name: Show Satellite variables
  hosts: all
  gather_facts: no
  tasks:
  - name: Show lifecycle_environment
    debug:
      msg: >
        lifecycle_environment: {{ hostvars[lifecycle_environment] }}

# ---
# - name: Extract Lifecycle Environment from All Satellite Hosts
#   hosts: all  # Target all hosts
#   gather_facts: no

#   tasks:
#     - name: Get hostvars for each host
#       debug:
#         var: hostvars[item].lifecycle_environment
#       loop: "{{ groups['all'] }}"
