---
- name: A full workflow that will call multiple roles
  hosts: all
  gather_facts: false

  vars:
    nexthop: somethingiwilloverride.example.org
    nexthop_port: 2525

  tasks:
  - name: call roles
    ansible.builtin.include_role:
      name: mxout
