---
- name: A full workflow that will call multiple roles
  hosts: all

  # Gather facts needed to retrieve hostname
  gather_facts: true

  vars:
    nexthop: somethingiwilloverride.example.org
    nexthop_port: 2525

  tasks:
  - name: call roles
    ansible.builtin.include_role:
      name: mxout
